     name: CI

     on:
       push:
         branches:
           - main
       pull_request:
         branches:
           - main
       schedule:
         - cron: '20 * * * *'  # 每个整点运行一次

     jobs:
       build:
         runs-on: ubuntu-latest

         steps:
         - name: Checkout code
           uses: actions/checkout@v4  # 更新到 v4

         - name: Set up Python
           uses: actions/setup-python@v4  # 更新到 v4
           with:
             python-version: '3.8'

         - name: Install dependencies
           run: pip install -r requirements.txt

         - name: Run tests
           run: pytest

       run_script:
         runs-on: ubuntu-latest
         if: github.event_name == 'schedule' || github.event_name == 'push'
         steps:
         - name: Checkout repository
           uses: actions/checkout@v4  # 更新到 v4

         - name: Set up Python
           uses: actions/setup-python@v4  # 更新到 v4
           with:
             python-version: '3.x'

         - name: Install dependencies
           run: |
             python -m pip install --upgrade pip
             pip install requests

         - name: Run script
           run: |
             python script.py

         - name: Commit and push changes
           run: |
             git config --global user.name 'github-actions[bot]'
             git config --global user.email 'github-actions[bot]@users.noreply.github.com'
             git add qgdf.txt
             git commit -m 'Update qgdf.txt'
             git push
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
