name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '10 0 * * *'    # 每天00:00 UTC时间运行爬取脚本（北京时间8:00）
    - cron: '10 12 * * *'   # 每天12:01 UTC时间运行爬取脚本（北京时间20:01）
    - cron: '15 0 * * *'    # 每天00:05 UTC时间运行测速脚本（北京时间8:05）
    - cron: '15 12 * * *'   # 每天12:05 UTC时间运行测速脚本（北京时间20:05）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 确保使用最新版本

    - name: Set up Python
      uses: actions/setup-python@v4  # 确保使用最新版本
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

  run_script:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'push'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 确保使用最新版本

    - name: Set up Python
      uses: actions/setup-python@v4  # 确保使用最新版本
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run script.py
      if: github.event.schedule == '10 0 * * *' || github.event.schedule == '10 12 * * *'
      run: python script.py

    - name: Run cs.py
      if: github.event.schedule == '15 0 * * *' || github.event.schedule == '15 12 * * *'
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install requests
        python cs.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'wanglu6036'
        git config --global user.email '376671120@qq.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git pull origin main  # 拉取最新的更改
        git add iptv.txt qgdf.txt
        git diff-index --quiet HEAD || git commit -m 'Update iptv.txt and qgdf.txt'
        git push origin main
