name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '55 * * * *'  # 每个整点运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 确保使用最新版本

    - name: Set up Python
      uses: actions/setup-python@v4  # 确保使用最新版本
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

  run_script:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'push'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 确保使用最新版本

    - name: Set up Python
      uses: actions/setup-python@v4  # 确保使用最新版本
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: |
        python script.py

    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name 'wanglulu'
        git config --global user.email '376671120@qq.com'
        git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
        git add qgdf.txt
        git commit -m 'Update qgdf.txt'
        git push origin main
